image: maven:3-jdk-8



stages:
  - build
  - test
  - package
  - deploy


maven-build:
  
  stage: build
  script: 
  - mvn package
  artifacts:
    paths:
      - target/*.jar

unit-testing:
  
  stage: test
  script:
  - mvn test
  
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

code-coverage:
  stage: test
  script:
    - 
    - 
  artifacts:
    paths:
      - target/


  only:
    - master
