image: maven:3-jdk-8



stages:
  - build
  - test
  - package
  - deploy


maven-build:
  
  stage: build
  script: 
  - mvn package
  artifacts:
    paths:
      - target/*.jar

test-reports:
  
  stage: test
  script:
  - mvn verify
  
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

unit-test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    - cat target/site/jacoco/index.html
  artifacts:
    paths:
      - target/site/jacoco/


  only:
    - master
