image: maven:3-jdk-8



stages:
  - build
  - test
  - package
  - deploy
  


maven-build:
  
  stage: build
  script: 
  - mvn package
  artifacts:
    paths:
      - target/*.jar

unit-testing:
  
  stage: test
  script:
  - mvn test
  
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        
Publish:

  stage: package
  script:
    - 'cp ci_settings.xml /root/.m2/settings.xml'
    - 'mvn deploy'
        

code-coverage:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    - cat target/site/jacoco/index.html
  artifacts:
    paths:
      - target/site/jacoco/



  only:
    - master
